/**
 * Production server: single port, no Vite.
 *  - `/api/*`      -> Elysia
 *  - `/assets/*`   -> hashed immutable client assets from build/client
 *  - other files   -> static files from build/client (favicon, etc.)
 *  - everything else -> React Router SSR handler from the compiled server build
 *
 * Run after `bun run build`.
 *
 * Single-file binary mode (bun build --compile --asset ./build/client):
 *   Bun bundles this file and follows the static import of the SSR bundle,
 *   pulling in @react-router/node and all other deps into the binary.
 *   Client assets are embedded via --asset and served via import.meta.dir.
 */
import path from 'node:path';
import { createRequestHandler, type ServerBuild } from 'react-router';
// @ts-ignore — generated by `react-router build`. In `bun build --compile` mode,
// Bun's bundler follows this static import and bundles the SSR module + all its
// dependencies (@react-router/node, react-dom, etc.) into the binary.
import * as ssrBuild from '../build/server/index.js';
import { api } from './api';
import { env } from './env';
import { logger } from './logger';
import { recordVisit } from './middleware/visitor';

const build = ssrBuild as unknown as ServerBuild;
const handler = createRequestHandler(build, 'production');

// In standalone binary: import.meta.dir = /$bunfs/root, assets embedded as 'client/' (stripped from ./build/client).
// In script mode: import.meta.dir = /path/to/server/, assets at ../build/client.
const CLIENT_DIR = Bun.isStandaloneExecutable
  ? path.join(import.meta.dir, 'client') + '/'
  : path.join(import.meta.dir, '../build/client') + '/';

const server = Bun.serve({
  port: env.PORT,
  idleTimeout: 60,
  async fetch(request) {
    const url = new URL(request.url);

    // API + auth.
    if (url.pathname.startsWith('/api')) {
      return api.handle(request);
    }

    // Static client assets.
    const filePath = CLIENT_DIR + url.pathname.replace(/^\/+/, '');
    const file = Bun.file(filePath);
    if (url.pathname !== '/' && (await file.exists())) {
      const immutable = url.pathname.startsWith('/assets/');
      return new Response(file, {
        headers: immutable
          ? { 'Cache-Control': 'public, max-age=31536000, immutable' }
          : { 'Cache-Control': 'public, max-age=3600' },
      });
    }

    // SSR. Record page visit (fire-and-forget — must not block response).
    void recordVisit(request, null);
    return handler(request);
  },
});

logger.info(`\u{1F680} Makuro production server on http://localhost:${server.port}`);
